from libqtile.utils import guess_terminal

myTerminal         = guess_terminal()
myTextEditor       = myTerminal + " -e vim"
myHtop             = myTerminal + " -e htop"
myFiles            = myTerminal + " -e vifmrun"
myCliMusic         = myTerminal + " -e ncmpcpp"
myVirtManager      = "virt-manager"
myAnki             = "anki"
myWebBrowser       = "qutebrowser"
myIncognitoBrowser = "qutebrowser --target private-window"
myTorBrowser       = "torbrowser-launcher"
myFileManager      = "pcmanfm"
myVideoPlayer      = "celluloid"
myGame             = "/usr/bin/steam-runtime %U"
myIde              = "emacsclient -c -a 'emacs'"
myImageEditor      = "gimp"
myVectorEditor     = "inkscape"
myVideoEditor      = "kdenlive"
myPhotoLibrary     = "digikam"
myTorrent          = "transmission-gtk"
myVpn              = "/opt/piavpn/bin/pia-client --quiet"
myVm               = "virtualbox"
myLauncher         = "rofi -show drun"
myPasswordManager  = "rofi-pass"
myCalculator       = "gnome-calculator"

myWhatsApp         = "whatsapp-for-linux"
myDiscord          = "discord"

myMyNetworkManager = "nm-connection-editor"
myBluetoothManager = "blueman-manager"
myPowerManager     = "xfce4-power-manager-settings"
myAudioManager     = myTerminal + " -e alsamixer"
